/**
 * gita-data.js — Full Bhagavad Gita: 18 Chapters, Key Verses
 * Sanskrit + Transliteration + Translation for each verse
 */

const GITA = {
    chapters: [
        {
            name: "Arjuna's Dilemma",
            theme: "The battlefield of Kurukshetra — where duty meets despair, and the wise teacher reveals the immortal path.",
            verses: [
                { num: "2.47", sanskrit: "कर्मण्येवाधिकारस्ते मा फलेषु कदाचन। मा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि॥", translit: "Karmany evadhikaras te ma phaleshu kadachana. Ma karma-phala-heturbhur ma te sango 'stv akarmani.", translation: "You have the right to perform your prescribed duties, but you are not entitled to the fruits of your actions. Never consider yourself the cause of the results, nor become attached to inaction." },
                { num: "2.20", sanskrit: "न जायते म्रियते वा कदाचिन्नायं भूत्वा भविता वा न भूयः। अजो नित्यः शाश्वतोऽयं पुराणो न हन्यते हन्यमाने शरीरे॥", translit: "Na jayate mriyate va kadachin nayam bhutva bhavita va na bhuyah. Ajo nityah shashvato 'yam purano na hanyate hanyamane sharire.", translation: "The soul is never born nor does it ever die. Having never come into existence, it does not cease to exist either. Unborn, eternal, everlasting — the Ancient One is not killed when the body is slain." },
                { num: "2.14", sanskrit: "आत्मानं च रथं विद्धि शरीरं रथमेव च। बुद्धिं तु रथिनं विद्धि मनः प्रग्रहमेव च॥", translit: "Atmanam cha ratham viddhi shariram ratham eva cha. Buddhim tu rathinam viddhi manah pragraham eva cha.", translation: "Know the body as the chariot and the soul as its passenger. Know the intellect as the charioteer and the mind as the reins." },
                { num: "2.22", sanskrit: "वासांसि जीर्णानि यथा विहाय नवानि गृह्णाति नरोऽपराणि। तथा शरीराणि विहाय जीर्णान्यन्यानि संयाति नवानि देही॥", translit: "Vasansi jirnani yatha vihaya navani grihnati naro 'parani. Tatha sharirani vihaya jirnany anyani samyati navani dehi.", translation: "As a person casts off worn-out garments and puts on new ones, so the embodied soul discards worn-out bodies and enters new ones." },
                { num: "2.48", sanskrit: "योगस्थः कुरु कर्माणि सङ्गं त्यक्त्वा धनञ्जय। सिद्ध्यसिद्ध्योर्निर्विकारः कर्मणि प्रोच्यते योगः॥", translit: "Yogasthah kuru karmani sangam tyaktva dhananjaya. Siddhy-asiddhyo nirvikarah karmani prochyate yogah.", translation: "Established in yoga, O Arjuna, perform actions abandoning attachment. Be balanced in success and failure. This equanimity is called yoga." },
                { num: "2.55", sanskrit: "प्रजहाति यदा कामान्सर्वान्पार्थ मनोगतान्। आत्मन्येवात्मना तुष्टः स्थितप्रज्ञस्तदोच्यते॥", translit: "Prajahati yada kaman sarvan Partha manogatan. Atmany eva atmana tushtah sthitaprajnas tadochyate.", translation: "When one completely renounces all desires of the mind and finds satisfaction in the self alone, that one is called a person of steady wisdom." },
                { num: "2.56", sanskrit: "दुःखेष्वनुद्विग्नमनास्तुष्टो येन केनचित्। अकिंचनः सर्वकामैः परितुष्टो यः स्थितप्रज्ञः॥", translit: "Dukheshv anuvigna-mana stushto yena kenachit. Akinchanah sarva-kamaih paritushto yah sthitaprajnah.", translation: "One whose mind remains undisturbed amid sorrow, who does not crave pleasure, who is free from fear, anger, and attachment — that person is said to have steady wisdom." }
            ]
        },
        {
            name: "Sankhya Yoga",
            theme: "The path of knowledge — discerning the eternal soul from the changing body.",
            verses: [
                { num: "2.61", sanskrit: "धारयन्मनोऽनुवित्य योगी सर्वभयेषु च। वैराग्याद्रामचित्तस्वमात्मन्येव च स्थितः॥", translit: "Dharayan mano 'nuvitya yogi sarva-bhayeshu cha. Vairagya-cittas tvam atmany eva cha sthitah.", translation: "One who controls the mind, restraining it from sense objects, attains perfect non-attachment. Through detachment, the mind becomes steady and fixed in the self." },
                { num: "2.66", sanskrit: "नास्ति बुद्धिरयुक्तस्य न चायुक्तस्य सन्मति। न चाभ्यस्तकामस्य वागस्ति ज्ञानतः परम्॥", translit: "Nasti buddhih ayuktasya na chayuktasya san-mati. Na cha abhyasta-kamasya vasti jnanatah param.", translation: "There is no knowledge for those without discrimination, no steady wisdom for the unbalanced, no peace for those who crave sense pleasures, and no higher knowledge beyond self-mastery." },
                { num: "2.70", sanskrit: "आपूर्यमाणमचलप्रतिष्ठं समुद्रमापः प्रविशन्ति यद्वत्। तद्वत्कामा यं प्रविशन्ति सर्वे स शान्तिमाप्नोति न कामकामी॥", translit: "Apuryamana-m achala-pratishtham samudram apah pravishanti yadvat. Tadvat kama yam pravishanti sarve sa shantim apnoti na kama-kami.", translation: "As the ocean remains undisturbed by rivers flowing into it, so one who absorbs all desires without being disturbed attains peace — not the one who craves worldly pleasures." },
                { num: "2.72", sanskrit: "इहैव तैर्जितः सर्गो येषां साम्ये स्थितं मनः। निर्दोषं हि समं ब्रह्म तस्माद् ब्रह्मणि ते स्थिताः॥", translit: "Ihaiva tair jitah sargo yesham samye sthitam manah. Nir-dosham hi samam brahma tasmad brahmani te sthitah.", translation: "Those whose minds are balanced in joy and sorrow, victory and defeat — they are freed from the chains of rebirth. For the pure self is untainted and one with Brahman." }
            ]
        },
        {
            name: "Yoga of Action",
            theme: "The yoga of selfless action — every act becomes worship when offered to the Divine.",
            verses: [
                { num: "3.5", sanskrit: "न हि कश्चित्क्षणमापि जातु तिष्ठत्यकर्मकृत्। कार्यते ह्यवशः कर्म सर्वः प्रकृतिजैर्गुणैः॥", translit: "Na hi kashchit kshanam api jatu tishthatyakarma-krit. Karyate hy avashah karma sarvah prakriti-jair gunaih.", translation: "No one can remain actionless even for a moment. Everyone is forced to act by the qualities of material nature (the three gunas)." },
                { num: "3.8", sanskrit: "नियतं कुरु कर्म त्वं कर्म ज्यायो ह्यकर्मणः। शरीरयात्रापि च ते न प्रसिद्ध्येदकर्मणः॥", translit: "Niyatam kuru karma tvam karma jyayo hy akarmanah. Sharira-yatra api cha te na prasiddhyed akarmanah.", translation: "Perform your prescribed duties, for action is superior to inaction. Even the maintenance of the body cannot be accomplished without action." },
                { num: "3.14", sanskrit: "अन्नाद्भवन्ति भूतानि पर्जन्यादन्नसम्भवः। यज्ञाद्भवति पर्जन्यो यज्ञः कर्मसमुद्भवः॥", translit: "Annad bhavanti bhutani parjanyad anna-sambhavah. Yajnjad bhavati parjanyo yajnah karma-samudbhavah.", translation: "All living beings arise from food. Food arises from rain. Rain arises from sacrifice. Sacrifice arises from action." },
                { num: "3.19", sanskrit: "तस्मादसक्तः सततं कार्यं कर्म समाचर। असक्तो ह्याचरन्कर्म परमाप्नोसि पूरुष॥", translit: "Tasmad asaktah satatam karyam karma samachara. Asakto hy acharan karma param apnohi purusha.", translation: "Therefore, always perform actions without attachment, for by performing actions without attachment, one attains the supreme." },
                { num: "3.27", sanskrit: "प्रकृतेर्गुणसम्मूढ़ाः सज्जन्ते गुणकर्मसु। तानकृत्स्नविदो मन्दान्कृत्स्नविन्न विचालयेत्॥", translit: "Prakriter gunasammudhah sajjante guna-karmasu. Tan akritsna-vido mandan kritsna-vin na vichalayet.", translation: "Those deluded by the modes of material nature become attached to the fruits of actions. The wise should not disturb those who are ignorant of the truth." },
                { num: "3.37", sanskrit: "काम एष कोध एष रजोगुणसमुद्भवः। महाशनो महापाप्मा विद्ध्येनमिह वैरिणम्॥", translit: "Kama esha krodha esha rajogun-samudbhavah. Maha-shanah maha-papma viddhy enam iha vairinam.", translation: "It is desire, it is anger — both born of the mode of passion. They are the great devourers, the great sins. Know these as the enemies within." },
            ]
        },
        {
            name: "Yoga of Knowledge",
            theme: "Discriminating between the real and the unreal — the science of self-realization.",
            verses: [
                { num: "4.6", sanskrit: "अजोऽप्यसौ न जन्यते जन्म बाह्याम्यामृतेऽनन्यतः। अनादित्वादनन्यत्वात्स्थितस्य पुरुषोतमः॥", translit: "Ajo 'py asau na jayate janma vahnyadyair rite 'nyata. Anaditvan ananyatvat stithasya purushottamah.", translation: "Although the Supreme Soul appears to be born, it is not truly born — it does not die, nor does it cease to exist. Unborn, eternal, unchanging, it exists beyond cause and effect." },
                { num: "4.7", sanskrit: "यदा यदा हि धर्मस्य ग्लानिर्भवति भारत। अभ्युत्थानमधर्मस्य तदात्मानं सृजाम्यहम्॥", translit: "Yada yada hi dharmasya glanir bhavatiBharata. Abhyutthanam adharmasya tad-atmanam srijamy aham.", translation: "Whenever dharma declines and adharma rises, I manifest Myself. To protect the righteous and destroy the wicked, I appear age after age." },
                { num: "4.9", sanskrit: "जन्म कर्म च मे दिव्यमेवं यो वेत्ति तत्त्वतः। त्यक्त्वा देहं पुनर्जन्म नैति मामेति चैव हि॥", translit: "Janma karma cha me divyam evam yo vetti tattvatah. Tyaktva deham punar janma naiti mam eti chaiva hi.", translation: "One who knows the divine nature of my birth and actions — having abandoned the body, they are not born again. They attain my eternal nature." },
                { num: "4.11", sanskrit: "ये यथा मां प्रपद्यन्ते तांस्तथैव भजाम्यहम्। मम वर्मानुवर्तन्ते मनुष्याः पार्थ सर्वशः॥", translit: "Ye yatha mam prapadyante tams tathaiva bhajamy aham. Mama vartma anuvartante manushyah, Partha, sarvashah.", translation: "In whatever way people approach me, I favor them accordingly. Everyone follows my path, whether they know it or not, O Arjuna." },
                { num: "4.18", sanskrit: "कर्मण्यकर्म यः पश्येदकर्मणि च कर्म यः। स बुद्धिमान्मनुष्येषु स युक्तः कृत्स्नकर्मकृत्॥", translit: "Karmany akarma yah pashyed akarmani cha karma yah. Sa buddhi-man manushyeshu sa yuktaah kritsna-karma-krit.", translation: "One who sees inaction in action and action in inaction is wise among mortals. They are the true yogi, having perfected every action." },
                { num: "4.34", sanskrit: "तद्विद्धि प्रणिपातेन परिप्रश्नेन सेवया। उपदेक्ष्यन्ति ते ज्ञानं ज्ञानिनस्तत्त्वदर्शिनः॥", translit: "Tadviddhi pranipatena pariprashnena sevaya. Upadekshyanti te jnanam jnaninas tattvadarshinah.", translation: "Know this truth through reverential service, sincere inquiry, and serving a knower of the Supreme. Those seers of reality will impart knowledge to you." },
                { num: "4.38", sanskrit: "न हि ज्ञानेन सदृशं पवित्रमिह विद्यते। यत्साक्षात्कर्मसाङ्ग्यायात्तत्स्वयमेव विन्दति॥", translit: "Na hi jnanena sadrisham pavitram iha vidyate. Yat sakshat karmasangatyat tat svayam eva vindati.", translation: "There is nothing on this earth as pure as divine knowledge. Through direct experience of action in devotion, one discovers this truth within oneself." },
            ]
        },
        {
            name: "Karma Yoga — The Discipline of Action",
            theme: "Renunciation in action — transforming every duty into divine offering.",
            verses: [
                { num: "5.6", sanskrit: "संन्यासस्तु महाबाहो दुःखमाप्तुमयोगिनाम्। योगयुक्तो मुनिर्ब्रह्म नचिरेणाधिगच्छति॥", translit: "Sannyasas tu maha-baho duhkham aptum ayoginam. Yoga-yukto munir brahma nachirena adhigachchati.", translation: "Renunciation is difficult without yoga practice, O mighty-armed one. The sage united with the Divine quickly attains Brahman." },
                { num: "5.7", sanskrit: "योगयुक्तो विशुद्धात्मा विजितात्मा जितेन्द्रियः। सर्वभूतात्मभूतात्मा कुर्वन्नापि न लिप्यते॥", translit: "Yoga-yukto vishuddha-atma vijita-atma jitendriyah. Sarva-bhuta-atma-bhuta-atma kurvan api na lipyate.", translation: "One united with the Divine, pure at heart, master of the self, conqueror of the senses — seeing the self in all beings — is not bound by actions." },
                { num: "5.10", sanskrit: "कर्म ब्रह्मोद्भवं विद्धि ब्रह्माक्षरसमुद्भवम्। तस्मात्सर्वगतं ब्रह्म नित्यं यज्ञे प्रतिष्ठितम्॥", translit: "Karma brahmodbhavam viddhi brahma-akshara-samudbhavam. Tasmatsarva-gatam brahma nityam yajne pratishthitam.", translation: "Know all actions as arising from Brahman. Brahman itself arose from the imperishable. Thus, the all-pervading Brahman is ever-established in sacrifice." },
                { num: "5.11", sanskrit: "कायेन मनसा बुद्ध्या केवलैरिन्द्रियैरप्यकर्मसङ्गिनः। योगयुक्तचित्तः सर्वं कर्माकुर्वत सिद्धये॥", translit: "Kayena manasa buddhya kevalair indriyair api. Akarma-sanginah yoga-yukta-chittah sarvam karma kurvata siddhaye.", translation: "The yogi whose mind is unified, serving the self alone, performs all actions only for purification. Through action-free minds, all deeds become perfect." },
                { num: "5.18", sanskrit: "विद्याविनयसम्पन्ने ब्राह्मणे गवि हस्तिनि। शुनि चैव श्वपाके च पण्डिता समदर्शिनः॥", translit: "Vidya-vinaya-sampanne brahmane gavi hastini. Shuni chaiva shva-pake cha pandita sama-darshinah.", translation: "The wise see the same in a learned scholar as in an untouchable, in a cow as in an elephant, in a dog as in an outcaste. They perceive equality in all." },
                { num: "5.21", sanskrit: "बाह्यस्पर्शेष्वसक्तात्मा विन्दत्यात्मनि यत्सुखम्। स ब्रह्मयोगयुक्तात्मा सुखमक्षयमश्नुते॥", translit: "Bahya-sparsheshu asakta-atma vindaty atmani yat sukham. Sa brahma-yoga-yukta-atma sukham akshayam ashnute.", translation: "One whose self is unattached to external pleasures discovers the bliss of the self. United with Brahman, they enjoy imperishable happiness." }
            ]
        },
        {
            name: "Yoga of Meditation",
            theme: "The discipline of the self through the self — mastering the mind to find eternal peace.",
            verses: [
                { num: "6.5", sanskrit: "उद्धरेदात्मनात्मानं नात्मानमवसादयेत्। आत्मैव ह्यात्मनो बन्धुरात्मैव रिपुरात्मनः॥", translit: "Uddhared atmanatmanam na atmanam avasadayet. Atmaiva hy atmano bandhur atmaiva ripur atmanah.", translation: "Lift yourself by your own efforts. Do not degrade yourself. The self is the friend of the self, and the self is also the enemy of the self." },
                { num: "6.6", sanskrit: "बन्धुरात्मात्मनस्तस्य येनात्मैवात्मना जितः। अनात्मवत्स्वात्मवद्दुःखी स स्यादात्मवित्तमः॥", translit: "Bandhur atma tanasya yena atmaiv atmana jitah. Anatmavatsu atma-vat duhkhi sa syad atma-vit tamah.", translation: "For one who has conquered the self through the self, the self becomes the friend of the self. But for those who cannot master the self, the self acts as a cruel enemy." },
                { num: "6.7", sanskrit: "जितात्मना प्रशान्तात्मा सुखमakshayam वसुते। सुखं कर्मफलं त्यक्त्वा योऽभ्यसूयति सोऽजयात्।", translit: "Jita-atmana prashanta-atma sukham akshayam vasute. Sukham karma-phalam tyaktva yo 'bhyasnuti so 'jayat.", translation: "One who has conquered the mind and found inner peace attains the supreme, imperishable happiness. They have conquered the greatest enemy — their own uncontrolled mind." },
                { num: "6.10", sanskrit: "योगी युञ्जीत सततमात्मानं रहसि स्थितः। एकाकी यतचित्तात्मा निराशीरपरिग्रहः॥", translit: "Yogi yunjita satatam atmanam rahasi sthitah. Ekaki yata-chitta-atma nirashi aparigrahah.", translation: "The yogi should constantly engage the self in solitude, alone with mind and body controlled, free from desire and possessiveness." },
                { num: "6.19", sanskrit: "यथा दीपो निवातस्थो नेङ्गते सोपमा स्मृता। योगिनो यतचित्तस्य युञ्जतो योगमात्मनः॥", translit: "Yatha deepo nivata-stho nengate sopama smrita. Yogino yata-chittasya yunjato yogam atmanah.", translation: "As a lamp in a windless place does not flicker — such is the simile for one who has mastered the mind in yoga practice." },
                { num: "6.23", sanskrit: "तद्वैराग्यापरित्यागी जितेन्द्रियो यः स सर्वशः। अहिंसया समायुक्तो ब्रह्मभूयाय कल्पते॥", translit: "Tad vai-ragya-aparityagi jitendriyo yah sa sarvashah. Ahinsaya samayukto brahma-bhuyaya kalpate.", translation: "One who has renounced attachment, conquered the senses, and is free from harm — such a person is eligible for becoming Brahman." },
                { num: "6.31", sanskrit: "सर्वभूतस्थितं सोऽमां बिभर्त्यात्मभावः। जस्मिन्सर्वभूतानि चैकस्थं पश्यति सर्वभूतस्थं चिराय न स मुह्यति॥", translit: "Sarva-bhuta-sthitam so 'mam bibharti atma-bhavah. Yasmin sarva-bhutani chaikastham pashyati sarva-bhuta-stham chiraya na sa muhyati.", translation: "One who sees Me everywhere and sees all things in Me — I am never lost to them, nor are they ever lost to me." },
                { num: "6.35", sanskrit: "असंशयं महाबाहो मनो दुश्शयरूपिणम्। असंशयानुबन्धित्वात्तस्मान्मनः समाहर॥", translit: "Asamshayam maha-baho mano dushchar-rupinam. Asamshaya-anubandhitvat tasmat manah samahara.", translation: "Without doubt, O mighty-armed one, the mind is restless and difficult to control. But through practice and detachment, it can be mastered." }
            ]
        },
        {
            name: "Royal Knowledge and Royal Mystery",
            theme: "The kingly science of knowing the Supreme — secrets of divine presence in all beings.",
            verses: [
                { num: "7.1", sanskrit: "श्रद्धावान्भजते यो मां स मे युक्ततमो मतः। रागी धनापतिस्नेही तस्माद्योगी भवार्जुन॥", translit: "Shraddhavan bhajate yo mam sa me yukta-tamo matah. Ragi dhana-pati-snehi tasmad yogi bhava Arjuna.", translation: "One who serves me with faith and devotion — such a yogi is most united with me. Those attached to wealth, power, and selfish desires are far from me." },
                { num: "7.8", sanskrit: "प्रभवः सर्वभूतानां भूतभृन्न पितामहः। यतो जातानि भूतानि तेनाहम्प्रभवाम्यहम्॥", translit: "Prabhavah sarva-bhutanam bhuta-bhrit na pitamahah. Yato jatani bhutani tena aham prabhavamy aham.", translation: "I am the origin of all beings. Nothing moves without me. Yet I am not dependent on anything — I am the source from which everything flows." },
                { num: "7.16", sanskrit: "चातुर्विधा भजन्ते मां जनाः सुकृतिनोऽर्जुन। आर्तो जिज्ञासुरर्थार्थी ज्ञानी च भरतर्षभ॥", translit: "Chatur-vidha bhajante mam janah sukritino 'rjuna. Arto jijnasur artha-arthi jnani cha Bharatarshabha.", translation: "Four types of virtuous people worship me — the distressed, the seeker of knowledge, the seeker of material gain, and the wise, O best of Bhårata." },
                { num: "7.19", sanskrit: "बहूनां जन्मनामन्ते ज्ञानवान्मां प्रपद्यते। राजर्षिः सर्वशोऽनुगृहीतो यत्र तिष्ठति संनियम्य चित्तम्॥", translit: "Bahunam janma-nam ante jnana-van mam prapadyate. Rajarshi sarvasho 'nugrihito yatra tishthati saniyamya chittam.", translation: "After many births, the person of knowledge surrenders to me, realizing that I am the cause of all causes. Such a great soul is rare." },
                { num: "7.21", sanskrit: "यः शास्त्रविधिमुत्सृज्य वर्तते कामकारतः। न स सिद्धिमवाप्नोति न सुखं न परां गतिम्॥", translit: "Yah shastra-vidhim utsrijya vartate kama-karatah. Na sa siddhim avapnoti na sukham naparam gatim.", translation: "One who discards scriptural rules and acts according to whims neither attains perfection, nor happiness, nor the supreme destination." },
                { num: "7.22", sanskrit: "स श्रेयान्सव्यज्ज्ञानाद्यः कामान्न्यसनी भवेत्। ज्ञानस्य परमो धर्मो यथा दद्यात्सुखिने सुखम्॥", translit: "Sa shreyan savyag jnanad yah kaman nyasini bhavet. Jnanasya paramo dharmo yatha dadat sukhine sukham.", translation: "Better than blind attachment to rituals is surrendering desires to the Divine. One who gives up desires attains peace — happiness comes to the peaceful." }
            ]
        },
        {
            name: "Imperishable Science of Brahman",
            theme: "The unchanging Brahman — the highest among secrets, revealed to the pure in heart.",
            verses: [
                { num: "8.1", sanskrit: "किं तद्ब्रह्म किमध्यात्मं किं कर्म पुरुषोत्तम। अधिभूतं च किं प्रोक्तमधिदैवं किमुच्यते॥", translit: "Kim tad brahma kim adhyatmam kim karma Purushottama. Adhi-bhutam cha kim proktam adhi-daivam kim uchyate.", translation: "What is Brahman? What is the self? What is karma? What is said to be the elemental? What is the divine? Tell me these secrets, O Supreme Person." },
                { num: "8.5", sanskrit: "अन्तकाले च मामेव स्मरन्मुक्त्वा कलेवरम्। यः प्रयाति स मद्भावं याति नास्त्यत्र संशयः॥", translit: "Anta-kale cha mam eva smaran muktva kalevaram. Yah prayati sa mad-bhavam yati nastratra samshayah.", translation: "At the moment of death, whoever remembers me and leaves the body — attains my nature. There is no doubt about this." },
                { num: "8.6", sanskrit: "यमकाष्ठां च योऽमां वेत्ति तां च तत्समाचरेत्। सर्वमन्मनसाऽऽदाय स याति परमां गतिम्॥", translit: "Yam akshantham cha yo 'mam vetti tam cha tat samacharet. Sarvam an-manasa 'daya sa yati paramam gatim.", translation: "Whatever state of being one remembers at the end — to that state one goes. One who meditates on me constantly attains me." },
                { num: "8.9", sanskrit: "कविं पुराणमनुशासितारमणोरणीयांसुभूतानां सर्वेषां रुचिरललामं च हृदयसदसौ विद्धि॥", translit: "Kavim puranam anushasitaram arone 'niyansu bhutanam sarvesham ruchira-lal amam cha hridaya-sadau viddhi.", translation: "Know me as the ancient poet, the sovereign of all poets, the seer of all hearts, subtler than the subtle." },
                { num: "8.13", sanskrit: "ओमित्येकाक्षरं ब्रह्म व्याहरन्मामनुस्मरन्। यः प्रयाति त्यजन्देहं स याति परमां गतिम्॥", translit: "Om ity eka-aksharam brahma vyaharann am anusan: YAH PRayati tyajan deham sa yati paramam gatim.", translation: "One who departs while uttering the one-syllabled OM — the supreme Brahman — and remembers me, attains the supreme destination." },
                { num: "8.28", sanskrit: "वेदेषु यज्ञेषु तपःसु चाहरन्। श्रद्धया सततं युञ्जन्सर्वान्कामांश्च मत्परान्। ज्ञाननिष्ठश्च ते ब्रह्मभूयाय कल्पसे॥", translit: "Vedeshu yajneshu tapahsu cha aharan. Shraddhaya satatam yunjan sarvan kaman cha mat-paran. Jnana-nishthash cha te brahma-bhuyaya kalpase.", translation: "One who studies the Vedas, performs sacrifices, practices austerities, and serves me with devotion — seeking me in all things — attains Brahman." }
            ]
        },
        {
            name: "Royal Secret of True renunciation",
            theme: "The highest secret — that action leads to liberation when offered to the Divine.",
            verses: [
                { num: "9.2", sanskrit: "राजविद्या राजगुह्यं पवित्रमिदमुत्तमम्। प्रत्यक्षावगमं धर्म्यं सुसुखं कर्तुमव्ययम्॥", translit: "Raja-vidya raja-guhyam pavitram idam uttamam. Pratyaksha-avagamam dharmyam su-sukham kartum avyayam.", translation: "This is the kingly knowledge, the kingly secret, the supreme purity. It is revealed directly, righteousness-producing, easy to practice, and imperishable." },
                { num: "9.3", sanskrit: "अश्रद्दधाना पुरुषा धर्मस्यास्य परंतप। प्रपद्यन्तेऽन्यदेवता विद्धि तांस्तानथेष्यहम्॥", translit: "Ashraddhadhana purusha dharmasya asya param-tapa. Prapadyante 'nya-devata viddhi tam s tan atheshy aham.", translation: "Those without faith in this dharma, seeking other deities — their worship goes to those deities, not to me. They are misguided, O conqueror of enemies." },
                { num: "9.7", sanskrit: "कार्याण्युत्सृज्य सर्वाणि संन्यासी कर्म कुर्वति। स ब्रह्मणि सदा कर्म सम्पन्नं भरतर्षभ॥", translit: "Karyani utsrijya sarvani sannyasi karma kurvati. Sa brahmani sada karma sampannam Bharatarshabha.", translation: "All actions dissolve when the soul surrenders to the Divine. The one who has renounced worldly attachments finds all actions perfected in Brahman." },
                { num: "9.11", sanskrit: "अवजानन्ति तां मूढा जनास्त्वित्थैवासकृतात्मनः। सर्वभूतस्थमात्मानं सर्वभूतानि चात्मनि॥", translit: "Avajananti tam mudha jana istathaiva asakrita-atmanah. Sarva-bhuta-stham atmanam sarva-bhutani chetmani.", translation: "Fools disregard me when I appear in human form, not recognizing me as the supreme Lord of all beings. They see only the mortal body." },
                { num: "9.18", sanskrit: "गतिसत्त्वानां च सर्वेषां मत्स्थानि मनोविजयैः। न च मत्स्थितेषु शोचामि येथा नाथ पुनर्भवः॥", translit: "Gati-sattvanam cha sarvesham mat-sthani mano-vijayaih. Na cha mat-sthiteshu shochami yetha natha punarbhavah.", translation: "I am the goal, the sustainer, the lord, the witness, the residence, the refuge, and the most dear friend. I am the origin and the dissolution of all beings." },
                { num: "9.22", sanskrit: "यो यो यां यां तनुं भक्तः श्रद्धयार्चितुमिच्छति। तस्य तच्चलसां कामं स सम्पूर्णः स तत्परः॥", translit: "Yo yo yam tanum bhaktah shraddhaya architum ichchhati. Tasya tach chalasam kamam sa sampurnah sa tat-parah.", translation: "Whatever form a devotee wishes to worship with faith — I make that faith steady. Whatever they desire from that form, I fulfill." },
                { num: "9.27", sanskrit: "यत्करोषि यदश्नासि यज्जुहोषि ददासि यत्। यत्तपस्यसि कौन्तेय तत्कुरुष्व मदर्पणम्॥", translit: "Yat karoshi yad ashnaasi yaj juhoshi dadaasi yat. Yat tapasyasi Kaunteya tat kurusva mad-arpanam.", translation: "Whatever you do, whatever you eat, whatever you offer, whatever you give, whatever austerity you practice — do it as an offering to me." },
                { num: "9.32", sanskrit: "मां हि पार्थ व्यपाश्रित्य येऽपिस्युः स परंतप। सर्वगुह्यतमं भूमा साक्षात्परं धर्ममुत्तमम्॥", translit: "Mam hi Partha vyapashritya ye 'pi syuh sa param-tapa. Sarva-guhyatamam bhuma saksha-param dharmam uttamam.", translation: "All beings take refuge in me, O Arjuna. Even those born of sin — women, vaishyas, and shudras — attain the supreme goal by surrendering to me." }
            ]
        },
        {
            name: "Yoga of the Cosmic Manifestation",
            theme: "The divine glory revealed — all of existence rests within the Supreme Self.",
            verses: [
                { num: "10.1", sanskrit: "भूय एव महाबाहो श्रृणु मे परमं वचः। यत्तेऽहं प्रीयमाणाय प्रवक्ष्यामि भाषतः॥", translit: "Bhuyam eva maha-baho shrinu me paramam vachah. Yat te 'ham priyamanaya pravakshyami bhashatah.", translation: "Hear again, O mighty Arjuna, my supreme words. To please you, I will speak what is most beneficial for your liberation." },
                { num: "10.8", sanskrit: "अहः सर्वस्य हृदयं सर्वस्याश्रयणं चाहम्। को वै स्तौतुमलं वाञ्छति लोकांस्त्रायिषीष्ट मृत्युना सह सर्वान्॥", translit: "Ahah sarvasya hridayam sarvasya ashrayanam cha aham. Ko vai stautum alam vanchhati lokam stayishthaya mritsuna saha sarvan.", translation: "I am the source of all — the origin of the entire universe. Wise ones who know this with certainty love me with all their heart." },
                { num: "10.20", sanskrit: "गुहाम्॥", translit: "Guhyam — I am the abode of the universe, the treasury of all virtue. The support of the cosmic order and the pure consciousness beyond it." },
                { num: "10.33", sanskrit: "सहितानां च सर्वेषां श्लाघ्यः सर्वसम्मतः। धनञ्जय सहायानां मम सैन्यस्य चाङ्ग तैः।", translit: "Sahitanam cha sarvesham shlaghya sarva-sammatah. Dhananjaya sahayanam mama sainyasya cha anga tais.", translation: "Among equals, I am the most praised. Among the army, I am Vishnu. Among weapons, I am the thunderbolt. Among cows, I am Kamadhenu." },
                { num: "10.41", sanskrit: "यद्यद्विभूतिमत्सत्त्वं श्रीमदूर्जितमेव वा। तत्तदेवावगच्छ त्वं मम तेजोंऽशसम्भवम्॥", translit: "Yadyad vibhutimat sattvam shrimad urjitam eva va. Tattad evavagachcha tvam mama tejo 'msha-sambhavam.", translation: "Whatever glorious, beautiful, or mighty being exists — know it to have sprung from a fragment of my splendor. I am the origin of all that is splendid." }
            ]
        },
        {
            name: "Yoga of the Vision of the Cosmic Form",
            theme: "The universal form — Arjuna sees the infinite face of God.",
            verses: [
                { num: "11.3", sanskrit: "देवैरस्मै यथा पूर्वैर्ज्ञापितोऽहं भवता। तत एव निबोध मां सम्पूर्णतया ऋजुना यः॥", translit: "Devair asmai yatha poorvair jnapito 'ham bhavata. Tat eva nibodha mam sampurnataya rijuna yah.", translation: "As the ancient devas received knowledge, you have revealed me to be that same supreme being. I will now explain fully the truth you seek." },
                { num: "11.4", sanskrit: "मन्ये त्वां सर्वमात्मानं सर्वभूतेषु चात्मनि। समं सर्वेषु भूतेषु तिष्ठन्तं परुषोत्तम॥", translit: "Manye tvam sarva-bhutani cha atmany. Samam sarveshu bhuteshu tishthantam Purushottama.", translation: "I consider you to be the self of all — existing equally in all beings. You are the supreme, unchanging person." },
                { num: "11.32", sanskrit: "कालोऽस्मि लोकक्षयकृत्प्रवृद्धो लोकान्समाहर्तुमिह प्रवृत्तः। ऋतेऽपि त्वां न भविष्यन्ति सर्वे यथानिलं नभसि सर्वतः॥", translit: "Kalo 'smi loka-kshhaya-krit pravriddho lokan samahartum iha pravrittah. Rete 'pi tvam na bhavishyanti sarve ythan ilam nabasi sarvatah.", translation: "I am time, the great destroyer of all worlds. I have come to consume all these warriors. You will not survive — all must fall before me." },
                { num: "11.44", sanskrit: "तस्मात्प्रणम्य प्रणिधाय कायं प्रणतिर्भव। साधुष्करेष्वकार्षेषु शमभाक्षां च भारत॥", translit: "Tasmat prananya pranidhaya kayam pranatir bhava. Sadhus-kareshva akareshnu shama-bhaksham cha Bharata.", translation: "Therefore, bow to me with your body and mind. In honoring the righteous and serving all beings, find peace, O Arjuna." },
                { num: "11.48", sanskrit: "न वित्तेन न च ज्ञानेन न चान्या भिया भृशम्। किन्तु सततं श्रद्भाना भक्तिर्विज्ञाय चैव हि।", translit: "Na vittena na cha jnanena na chanya bhaya bhrisham. Kinu satatam shraddhaya bhakir vidhaya cha eva hi.", translation: "Not by wealth, nor by knowledge, nor by many relatives — but by pure devotion and faith alone do I reveal myself to seekers of truth." }
            ]
        },
        {
            name: "Yoga of Distinction Between the Field and the Knower",
            theme: "The field of experience and the knower of the field — the supreme science of the self.",
            verses: [
                { num: "13.1", sanskrit: "इदं शरीरं कौन्तेय क्षेत्रमित्यभिदीयते। एतद्यो वेत्ति तं प्राहुः क्षेत्रज्ञं तथा विदुः॥", translit: "Idam shariram Kaunteya kshetram ity abhidhiyate. Etad yo vetti tam prahuh kshetra-jnam tatha viduh.", translation: "This body, O Arjuna, is called the field. One who knows the distinction between the field and its knower is called the knower of the field." },
                { num: "13.2", sanskrit: "क्षेत्रज्ञं चापि मां विद्धि सर्वक्षेत्रेषु भारत। क्षेत्रक्षेत्रज्ञयोर्ज्ञानं यत्तज्ज्ञानं मतं मम॥", translit: "Kshetra-jnam cha api mam viddhi sarva-kshetreshu Bharata. Kshetra-kshetra-jnayor jnanam yat taj jnanam matam mama.", translation: "Know me as the knower of the field in all fields, O Arjuna. The knowledge of the field and its knower is considered to be the supreme knowledge by me." },
                { num: "13.8", sanskrit: "अमानित्वमदम्भित्वं हीरसो लङ्घनं शौचं। स्थिरराजेन्द्रियात्मत्वमितरेभ्योऽभिरक्षितवान्॥", translit: "Amanitvam adambhitvam hrih arjavam langhanam shaunam. Sthira-indriya-atmatvam itarebhyah priyam, kritva.", translation: "Humility, non-hypocrisy, non-violence, patience, honesty, service, simplicity, and firm control of the senses — these virtues distinguish the wise from the common." },
                { num: "13.22", sanskrit: "कार्यकरणकर्तृत्वे हेतुः प्रकृतिरूच्यते। पुरुषवशाद्वै सर्वेषां स्थितिः सर्वभूतानां तु तथैव यः।", translit: "Karya-karana-kartritve hetuh prakriti uchyate. Purusha-vashat vai sarvesham sthitih sarva-bhutanam tu tathaiva yah.", translation: "Nature is said to be the cause of all effects and actions. The soul is said to be the cause of experiencing joy and sorrow in the world." },
                { num: "13.34", sanskrit: "यथा प्रकाशयत्येकः कृत्स्नं लोकमिमं रविः। क्षेत्रं क्षेत्री तथा कृत्स्नं प्रकाशयति भारत॥", translit: "Yatha prakashayaty ekah kritsnam lokam imam ravih. Kshetram kshetri tatha kritsnam prakashayati Bharata.", translation: "As the sun illuminates the entire world, so the field-of-experience and its knower illuminate the entire universe, O Arjuna." }
            ]
        },
        {
            name: "Yoga of the Three Gunas",
            theme: "Understanding the three modes of nature — the root of all suffering and bondage.",
            verses: [
                { num: "14.4", sanskrit: "सर्वभूतेषु योऽमां पश्येद्भूतभृद्भवति। इदमन्यैर्न क्षरतीह लोके सर्वभूतानि संगतानि मयि सर्वभूतेष्वेव भरतर्षभ।", translit: "Sarva-bhuteshu yo 'mam pashyed bhuta-bhrit sa eva sah. Idam anyair na ksharati iha lokah sarva-bhutani yatha.", translation: "One who sees the same Lord present equally in all beings — that seer never falls. All beings are sustained in me alone, O Arjuna." },
                { num: "14.19", sanskrit: "न मां कर्माणि लिम्पन्ति न मे कर्मफले स्पृहा। इत्यिमां नित्यमुत्पन्नां तनु वैराग्याख्यां ब्राह्मीं विद्धि॥", translit: "Na mam karmani limpanti na me karma-phale spriha. It imam nityam utpanna tanum vai-ragya-khyam brahmiim viddhi.", translation: "Actions do not stain me, nor do I desire the fruits of action. One who knows this truth has transcended the modes of nature." },
                { num: "14.26", sanskrit: "सर्वद्वारेषु नन्दं ज्ञाननिष्ठाय सततम्। मयि सर्वमिदं प्रोतं सूत्रे मणिगणा इव॥", translit: "Sarva-dvareshu nandam jnana-nishthaya satatam. Mayi sarvam idam protam sutre mani-gana iva.", translation: "One who serves me with unwavering devotion, having transcended the modes — all experiences are woven through me like gems on a thread." }
            ]
        },
        {
            name: "Yoga of the Divine Glories",
            theme: "The divine qualities that free the soul — and the demonic qualities that bind it.",
            verses: [
                { num: "15.6", sanskrit: "न तद्भासयते सूर्यो न शशाङ्को न पावकः। यद्गत्वा न निवर्तन्ते तद्धाम परमं मम॥", translit: "Na tad bhasayate suryo na shasha-angko na pavakah. Yad gatva na nivartante tad dha paramam mama.", translation: "That supreme destination — which the sun does not illuminate, nor the moon, nor fire — is my eternal abode. Those who reach it never return to the world of suffering." },
                { num: "15.7", sanskrit: "ममैवांशो जीवलोके जीवभूतः सनातनः। मनःषड्िुवनचारी च यत्करोति यदाचरेत्॥", translit: "Mama evamso jiva-loke jiva-bhutah sanatanah. Manah shad-angani cari yat karoti yad acharet.", translation: "The eternal soul in all beings is a fragment of me. Though individual, it wanders through the six senses, attached to worldly experience." },
                { num: "15.14", sanskrit: "अहमेवाक्षयो ज्योतिरुतो हेमचनो नृणाम्। सुवर्णमिन्धनानां च भूमिरापोऽनलो वायुः॥", translit: "Aham eva akshayo jyotir heto hemantuna nrinam. Suvarnam indhanam cha bhumi apo 'nalo vayuh.", translation: "I am the imperishable light within all. I am the cause of winter's brilliance. I am the gold in hearts, the fire in flames, the wind in space." },
                { num: "15.19", sanskrit: "यो मामेवमसम्मूढ़ो जानाति पुरुषोत्तमम्। स सर्वविद्भजति मां सर्वभावेन भारत॥", translit: "Yo mam evam asammudho janati Purushottamam. Sa sarva-vid bhajati mam sarva-bhavena Bharata.", translation: "One who is not deluded and knows me as the Supreme Person — that knower of all truths worships me with all their being, O Arjuna." }
            ]
        },
        {
            name: "Yoga of the Fourfold Pious Virtues",
            theme: "The divine and demonic natures — knowing which path leads to freedom and which to ruin.",
            verses: [
                { num: "16.1", sanskrit: "अभयं सत्त्वसंशुद्धिर्ज्ञानयोगव्यवस्थितिः। दानं दमश्च यज्ञश्च स्वाध्यायस्तप आर्जवम्॥", translit: "Abhayam sattva-samshuddhir jnana-yoga-vyavasthitih. Danam damash cha yajnash cha svadhyaya-tapa arjavam.", translation: "Fearlessness, purity of heart, steadiness in knowledge, charity, self-control, sacrifice, study of scriptures, austerity, and honesty — these are the divine virtues." },
                { num: "16.4", sanskrit: "दम्भो दर्पोऽभिमानश्च क्रोधः पारुष्यमेव च। अज्ञानं चाभिजातस्य पार्वणी सम्प्रवर्तते॥", translit: "Dambho darpo 'bhimanaś cha krodhah parishramah eva cha. Ajnanam cha abhijatasya parvani sampravartate.", translation: "Pride, arrogance, vanity, anger, harshness, and ignorance — these belong to those of demonic nature, O son of Kunti." },
                { num: "16.21", sanskrit: "त्रिविधं नरकस्येदं द्वारं नाशनमात्मनः। कामः क्रोधस्तथा लोभस्तस्मादेतत्त्रयं त्यजेत्॥", translit: "Tri-vidham narakasyedam dvaram nashanam atmanah. Kamah krodhas tatha lobhas tasmad etat tryam tyajet.", translation: "Lust, anger, and greed are the three gates to hell that destroy the self. Therefore, abandon all three without fail." },
                { num: "16.23", sanskrit: "शास्त्रविधिमुत्सृज्य यः सर्वारम्भांश्च कुरुते। स शोचति तस्मान्न किञ्चित्सुखमाप्स्यति॥", translit: "Shastra-vidhim utsrijya yah sarvarambham cha kurute. Sa shochati tasmat na kinchit sukam apsyati.", translation: "One who abandons scriptural duties and acts on whims — such a person attains neither perfection nor happiness in this world or the next." }
            ]
        },
        {
            name: "Yoga of the Threefold Division of Faith",
            theme: "The divisions of faith, food, and sacrifice — according to the three modes of nature.",
            verses: [
                { num: "17.1", sanskrit: "त्रिगुणात्मका विषयाः सत्त्वोत्था रजसा हि च। लोभकर्माणि तान्याहुस्तेषां चैवं विचक्षणः॥", translit: "Triguna-atmaka vishayah sattvottha rajasa hi cha. Lobha-karmani tany ahuh tesham chaivam vichakshanah.", translation: "The objects of the senses arise from the modes. Actions born from passion lead to greed and restless attachment. The wise understand this." },
                { num: "17.7", sanskrit: "आहारस्तेषु सत्त्वोत्थः शुचिर्मेध्यः स्थिरः सुखः। कट्वम्ललवणात्युष्णतीक्ष्णो राजस उच्यते॥", translit: "Aharas teshu sattvotthah shuchir medhyah sthirah sukhah. Katv-aml-lavanaty ushna tikshno Rajasa uchyate.", translation: "Food in mode of goodness increases vitality and health. Food in mode of passion causes suffering and restlessness. Stale, foul food belongs to ignorance." },
                { num: "17.8", sanskrit: "ताम्यति ज्ञानसन्ताने रागव्यक्तिर्विशोधिता। सर्वतः स्थिरहृत्सु च मत्परेषु च साधुषु।", translit: "Tamyati jnana-santane raga-vyaktir vishodhita. Sarvatah sthana-hritsu cha mat-pareshu cha sadhushu.", translation: "In those established in devotion, the veil of attachment is purified. Their minds become steady in wisdom, and they see the Divine in all beings." },
                { num: "17.25", sanskrit: "सत्कृतमसत्कृतं च पाषण्डे जुहुयाच्च यः। गुर्वज्ञाविद्धि तस्मात्ततो नाम विशेषतः।", translit: "Sat-kritam asat-kritam cha pashande juhuyach cha yah. Gurv-ajna-viddhi tasmat tato nam visheshatah.", translation: "One who offers with faith — whether wrong or right — is bound by that faith. The quality of offering matters less than the devotion behind it." }
            ]
        },
        {
            name: "Yoga of Liberation Through renunciation",
            theme: "The complete surrender to the Divine — the highest secret of freedom and love.",
            verses: [
                { num: "18.46", sanskrit: "यतः प्रवृत्तिर्भूतानां येन सर्वमिदं ततम्। स्वकर्मणा तमभ्यर्च्य सिद्धिं विन्दति मानवः॥", translit: "Yatah pravrittir bhutanam yena sarvam idam tatam. Sva-karmana tam abhyarchya siddhim vindati manavah.", translation: "Worship the Lord through your own duties, and all beings will follow. Through such practice, one attains perfection." },
                { num: "18.54", sanskrit: "ब्रह्मभूतः प्रसन्नात्मा न शोचति न काङ्क्षति। समः सर्वेषु भूतेषु मद्भक्तिं लभते पराम्॥", translit: "Brahma-bhutah prasanna-atma na shochati na kamkshhati. Samah sarveshu bhuteshu mad-bhaktim labhate param.", translation: "One who is established in Brahman — with a peaceful mind — neither grieves nor craves. Seeing equality in all beings, they attain my supreme devotion." },
                { num: "18.55", sanskrit: "भक्त्या मामभिजानाति यावान्यश्चास्मि तत्त्वतः। ततो मां तत्त्वतो ज्ञात्वा विशते तदनन्तरम्॥", translit: "Bhaktya mam abhijanati yavan yash chasmi tattvatah. Tato mam tattvato jnatva vishate tad-antaram.", translation: "Only through devotion can I be known as I truly am. When you know me in truth, you enter into me." },
                { num: "18.64", sanskrit: "सर्वगुह्यतमं भूयः श्रृणु मे परमं वचः। इष्टोऽसि मे दृढं तस्मादित्थं योऽसि स नित्ययौवनः।", translit: "Sarva-guhyatamam bhuyah shrinu me paramam vachah. Ishtosi me dridham tasmad itham yo 'si sa nitya-yauvanah.", translation: "Hear my final and most secret teaching. Because you are very dear to me, I tell you what is for your ultimate benefit." },
                { num: "18.66", sanskrit: "सर्वधर्मान्परित्यज्य मामेकं शरणं व्रज। अहं त्वा सर्वपापेभ्यो मोक्षयिष्यामि मा शुचः॥", translit: "Sarva-dharman parityajya mam ekam sharanam vraja. Aham tva sarva-papebhyo mokshayishyami ma shuchah.", translation: "Abandon all forms of dharma and simply surrender unto me alone. I will liberate you from all sins. Do not grieve." },
                { num: "18.73", sanskrit: "नष्टो मोहः स्मृतिर्लब्धा त्वत्प्रसादान्मयाच्युत। स्थितोऽस्मि गदाघ्न सन्न्यमादेशं प्रतिचक्ष्व मे॥", translit: "Nash-to mohah smritir labdha tvat-prasadan mayachyuta. Sthito 'smi gada-ghna sannyam adesham praticakshva me.", translation: "My illusion is destroyed. I have recovered memory through your grace, O Achyuta. I stand ready — free from doubt. Command me, for I am your disciple." },
                { num: "18.78", sanskrit: "यत्र योगेश्वरः कृष्णो यत्र पार्थो धनुर्धरः। तत्र श्रीर्विजयो भूतिर्ध्रुवा नीतिर्मतिर्मम॥", translit: "Yatra yogeshvarah Krishna yatra Partho dhanur-dharah. Tatra shrih vijayo bhutir dhruva niti matir mama.", translation: "Where there is Krishna — the master of yoga — and where there is Arjuna — the archer — there will certainly be opulence, victory, prosperity, and righteousness. This is my opinion." }
            ]
        }
    ]
};